### ISSUE TITLE
Dosen't work with Ruby Enterprise Edition

### ISSUE THREAD

**Issue by shaliko** [dougfales/gpx#1]
Generate error "TypeError: The first argument must be a document or node " on Ruby Enterprise Edition.

TypeError: The first argument must be a document or node.
    /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/libxml-ruby-1.1.4/lib/libxml/node.rb:57:in `register_namespaces_from_node'
    /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/libxml-ruby-1.1.4/lib/libxml/node.rb:57:in `context'
    /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/libxml-ruby-1.1.4/lib/libxml/node.rb:71:in `find'
    gpx (0.6) [v] lib/gpx/point.rb:42:in `initialize'
    gpx (0.6) [v] lib/gpx/trackpoint.rb:31:in `initialize'
    gpx (0.6) [v] lib/gpx/segment.rb:51:in `new'
    gpx (0.6) [v] lib/gpx/segment.rb:51:in `initialize'
    gpx (0.6) [v] lib/gpx/segment.rb:50:in `each'
    gpx (0.6) [v] lib/gpx/segment.rb:50:in `initialize'
    gpx (0.6) [v] lib/gpx/track.rb:46:in `new'
    gpx (0.6) [v] lib/gpx/track.rb:46:in `initialize'
    gpx (0.6) [v] lib/gpx/track.rb:45:in `each'
    gpx (0.6) [v] lib/gpx/track.rb:45:in `initialize'
    gpx (0.6) [v] lib/gpx/gpx_file.rb:83:in `new'
    gpx (0.6) [v] lib/gpx/gpx_file.rb:83:in `initialize'
    gpx (0.6) [v] lib/gpx/gpx_file.rb:82:in `each'
    gpx (0.6) [v] lib/gpx/gpx_file.rb:82:in `initialize'

**Comment by andrewhao** [comment]
Closing, as 1.8 is EOLed.
