### ISSUE TITLE
bump version to 0.9 and publish it to rubygems

### ISSUE THREAD

**Issue by doc75** [dougfales/gpx#12]
Hello,

After merging PR #11, would it be possible to bump version to 0.9 and publish it to rubygems ?

Thanks.

**Comment by andrewhao** [comment]
I'm going to publish it as v0.8.1 - hang tight.

**Comment by andrewhao** [comment]
Done. Let me know if this works for you.

**Comment by doc75** [comment]
@andrewhao This is perfect. Thanks.
