### ISSUE TITLE
The problem with parsing file

### ISSUE THREAD

**Issue by shaliko** [dougfales/gpx#2]
The problem with parsing file from official site http://www.topografix.com/gpx_sample_files.asp

gpx = GPX::GPXFile.new(:gpx_file => "#{RAILS_ROOT}/test/fixtures/fells_loop.gpx")
/opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/libxml-ruby-1.1.4/lib/libxml/node.rb:57: [BUG] Segmentation fault
ruby 1.8.7 (2009-12-24 patchlevel 248) [i686-darwin10.2.0], MBARI 0x6770, Ruby Enterprise Edition 2010.01

Abort trap

**Comment by andrewhao** [comment]
See #1
