### ISSUE TITLE
Accept StringIO and TempFile

### ISSUE THREAD

**Issue by Qwertie-** [dougfales/gpx#34]
[This line](https://github.com/dougfales/gpx/blob/master/lib/gpx/gpx_file.rb#L35) checks if the input is of the the type File. It would be helpful if it also accepted Tempfile and StringIO so you could give it the result of open-uri to load gpx files from http.

**Comment by tyrauber** [comment]
This issue is resolved [here](https://github.com/dougfales/gpx/blob/master/lib/gpx/gpx_file.rb#L38).
```
To read a GPX file from a string, use :gpx_data.
gpx_file = GPXFile.new(:gpx_data => '<xml ...><gpx>...</gpx>')
```
The Readme should be updated to reflect this.

**Comment by niborg** [comment]
This was implemented [here](https://github.com/dougfales/gpx/pull/55). README has been updated [here](https://github.com/dougfales/gpx/commit/fde464bc11613233147be14e842cf7470b26c3bd) as well.
