### ISSUE TITLE
New contributors?

### ISSUE THREAD

**Issue by andrewhao** [dougfales/gpx#44]
Hey @dougfales - pulling a long thread here. I'm not really able to devote much time to gem maintenance these days, and would like to find another contributor to move this gem forward. Would you be open to doing so? Folks like @niborg have volunteered in the past (not to put you on the spot!) but might be good to explicitly put out a call for a maintainer in the README, if you are open. WDYT?

**Comment by niborg** [comment]
I'm open to it! I still use the gem in one of my [side projects](https://www.hellodrifter.com), which is active, so I'm prone to catching bugs and the like.

**Comment by moveson** [comment]
I'm glad to hear there is interest here. In particular, I'd love to see https://github.com/dougfales/gpx/pull/43 get merged so we can keep this gem viable for Ruby 3. Thanks in advance @niborg and @andrewhao, very much appreciated.

**Comment by dougfales** [comment]
Hey @andrewhao, thanks for bringing this up! And thanks for your work on this repo over the past years. I'd be totally happy to add you as a maintainer @niborg. I'll invite you now. 

Do you think we need to put out a call for additional maintainers in the README? I'm ok with that too if it would help to have a couple extra people to merge PRs and manage releases.

**Comment by niborg** [comment]
@dougfales @andrewhao thank you, I'm happy to try to keep this gem moving along.

As for rubygems access, would simplest be to [add RubyGem secrets to the repository](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) so we can set up automatically pushing to rubygems on master branch updates? I think @dougfales only you can do this.

**Comment by andrewhao** [comment]
> Do you think we need to put out a call for additional maintainers in the README? I'm ok with that too if it would help to have a couple extra people to merge PRs and manage releases.

@dougfales I think that would be a great idea.

**Comment by niborg** [comment]
@andrewhao or @dougfales can either of you give me permissions to cut a release on rubygems? username is same as here.

**Comment by andrewhao** [comment]
I do not! @dougfales can you do that?
