### ISSUE TITLE
Would you consider changing the license on the library?

### ISSUE THREAD

**Issue by andrewhao** [dougfales/gpx#5]
I'd love to work on it under an OSS license. Thoughts?

**Comment by dougfales** [comment]
Definitely. I should have done that in the first place. I've added [an MIT license file](https://github.com/dougfales/gpx/commit/a10f06994b62b38fadb7c4bc657e57d786a0ddc5) and [updated the README](https://github.com/dougfales/gpx/commit/028f9d12d5c3314ff73b4680b28847a98d6f5ada) to reflect the new license.

Let me know if you need anything else from me. Thanks!
